<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Communities [
<!ELEMENT Communities (Community+)>
<!ELEMENT Community (Attribute+, Entity*)>
<!ATTLIST Community Name CDATA #REQUIRED>

<!ELEMENT AttributeID EMPTY>
<!ATTLIST AttributeID ID CDATA #REQUIRED>
<!ATTLIST AttributeID Access (manager|member|associate|world) #IMPLIED>

<!ELEMENT Entity (Attribute*)>
<!ATTLIST Entity Name CDATA #REQUIRED>

<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute ID CDATA #REQUIRED>
<!ATTLIST Attribute Value CDATA #REQUIRED>
]>
<Communities>

  <!--
    Example of a logistics (domain) community that has 5 members and provides 2
    externally visible roles.  Both external roles are provided by the agent
    "21-TSC-HQ".
  -->
  <Community Name="21-TSC">
    <Attribute ID="CommunityType"     Value="Domain" />
    <!-- If CommunityManager attribute is not empty only the agents listed
         are permitted to write to this community context. -->
    <Attribute ID="CommunityManager"  Value="" />
    <Entity Name="21-TSC-HQ" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="ExternalRole" Value="AmmoSupplyProvider" />
      <Attribute ID="ExternalRole" Value="TransportProvider" />
    </Entity>
    <Entity Name="11-ORDCO" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="AmmoSupplyProvider" />
    </Entity>
    <Entity Name="22-ORDCO" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="AmmoSupplyProvider" />
    </Entity>
    <Entity Name="33-TRKCO" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="TransportProvider" />
    </Entity>
    <Entity Name="44-TRKCO" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="TransportProvider" />
    </Entity>

  </Community>

  <!--
    Example of a restart community that has 5 members.  The Management Agent
    for this community is identified as an "Associate" with the Roles
    of "ManagementAgent" and "HealthReportConsumer".
  -->
  <Community Name="21-TSC-Enclave" >
    <Attribute ID="CommunityType"    Value="Robustness" />
    <Attribute ID="CommunityManager" Value="RestartAgent-1" />
    <Entity Name="21-TSC-HQ" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="11-ORDCO"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="22-ORDCO"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="33-TRKCO"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="44-TRKCO"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="RestartAgent-1" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Associate" />
      <Attribute ID="Role"         Value="ManagementAgent" />
      <Attribute ID="Role"         Value="HealthReportConsumer" />
    </Entity>
  </Community>

  <Community Name="MiniTestConfig-COMM" >
    <Attribute ID="CommunityType"    Value="Domain" />
    <Attribute ID="CommunityManager" Value="" />
    <Entity Name="MiniTestConfigNode" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="NodeAgent" />
    </Entity>
    <Entity Name="1BDE" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="TestRole" />
    </Entity>
    <Entity Name="3-69-ARBN"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="3ID"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="MCCGlobalMode"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="MiniTestConfigEnclave-COMM"  >
      <Attribute ID="EntityType"   Value="Community"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
  </Community>

  <Community Name="MiniTestConfigEnclave-COMM" >
    <Attribute ID="CommunityType"    Value="Domain" />
    <Attribute ID="CommunityType"    Value="Robustness" />
    <Attribute ID="CommunityManager" Value="" />
    <Entity Name="1BDE" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
      <Attribute ID="Role"         Value="TestRole" />
    </Entity>
    <Entity Name="3-69-ARBN"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="3ID"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="MCCGlobalMode"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Manager"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="ManagementAgent" />
      <Attribute ID="Role"         Value="HealthReportConsumer" />
    </Entity>
  </Community>

  <Community Name="Test-COMM" >
    <Attribute ID="CommunityType"    Value="Domain" />
    <Attribute ID="CommunityManager" Value="TestNode" />
    <Entity Name="TestNode" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="NodeAgent" />
    </Entity>
    <Entity Name="Agent01" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent02"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent03"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent04"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent05"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent06"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent07"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent08"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent09"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent10"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent11" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent12"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent13"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent14"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent15"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent16"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent17"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent18"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent19"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent20"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent21" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent22"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent23"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent24"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent25"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent26"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent27"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent28"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent29"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent30"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent31" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent32"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent33"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent34"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent35"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent36"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent37"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent38"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent39"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent40"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent41" >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent42"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent43"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent44"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent45"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent46"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent47"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent48"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent49"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
    <Entity Name="Agent50"  >
      <Attribute ID="EntityType"   Value="Agent"  />
      <Attribute ID="Role"         Value="Member" />
    </Entity>
  </Community>

  </Communities>
